### ISSUE TITLE
Cannot build Dockerfile

### ISSUE THREAD

**Issue by davidroberson** [cancerit/cgpbox#12]
I cannot build the Dockerfile.  Fails at # PCAP-core.  Using release 2.0.

```
Building and testing Bio-BigFile-1.07 ... ! Installing Bio::DB::BigFile failed. See /root/.cpanm/work/1471547787.8447/build.log for details. Retry with --force to force install it.
FAIL
INFO[0480] The command [/bin/sh -c curl -L -o master.zip --retry 10 https://github.com/ICGC-TCGA-PanCancer/PCAP-core/archive/master.zip &&     mkdir /tmp/downloads/distro &&     bsdtar -C /tmp/downloads/distro --strip-components 1 -xf master.zip &&     cd /tmp/downloads/distro &&     ./setup.sh $OPT &&     cd /tmp/downloads &&     rm -rf master.zip /tmp/downloads/distro /tmp/hts_cache] returned a non-zero code: 1 

```

**Comment by keiranmraine** [comment]
This is due to an issue in the underlying library:

https://github.com/GMOD/GBrowse-Adaptors/issues/16

If I can reproduce I will patch the underlying test during install as indicated in the linked ticket.

**Comment by keiranmraine** [comment]
Please see the [dockstore-cgpwgs](https://github.com/cancerit/dockstore-cgpwgs) repository and [dockstore.org](https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpwgs) integration.

This repository is soon to be retired.
