### ISSUE TITLE
X11 display problem with --user parameters in docker

### ISSUE THREAD

**Issue by mksamur** [cancerit/cgpbox#16]
It occurred to me that if I set --user parameters for docker run I got following error and based on some google search I would guess it is because of Rprofile  settings. Is there any known solution for this problem? 

Error in .External2(C_X11, paste("png::", filename, sep = ""), g$width,  :
  unable to start device PNG
Calls: ascat.plotRawData -> png
In addition: Warning message:
In png(filename = paste(ASCATobj$samples[i], ".tumour.png", sep = ""),  :
  unable to open connection to X11 display ''
Execution halted

**Comment by keiranmraine** [comment]
It is not appropriate to change the from the default user (cgpbox).

Please see the [dockstore-cgpwgs](https://github.com/cancerit/dockstore-cgpwgs) repository and [dockstore.org](https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpwgs) integration.

This repository is soon to be retired.
