### ISSUE TITLE
Dockerfile can't create image

### ISSUE THREAD

**Issue by jinchen-umich** [cancerit/cgpbox#17]
I tried to use Dokcerfile to create image. But meet some problems. 
1. cgpBigWig is not installed before  PCAP-core
2. no python 

Could you please update the latest Dockerfile?

Thanks!

**Comment by keiranmraine** [comment]
Hi,

We are in the process of migrating this project to a more granular framework and it will soon be retired.  If you still wish to use this please pick up the pre-built image available on quay.io:

https://quay.io/repository/wtsicgp/cgp_in_a_box?tab=tags

We are aware of a bug which results in the filtering of SVN's not being fully applied.

The new home for this will eventually dockstore and associated repositories (built in such a way that changes to underlying code won't instantly break the build of the container).  There are now 3 toolsets:

* [Mapping](https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap) - Maps from fastq/BAM/CRAM to a remapped BAM (or CRAM depending on your selected options) as CGP would recommend.  This ensures compatibility with downstream tools.
[WXS analysis](https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpwxs) - Perform Indel and SNV calling with Exome specific filtering.
[WGS analysis](https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpwgs) - Performs genotype, gender and contamination checks.  Executes Indel, SNV, CopyNumber, SV calling.  Also runs the first stages of Battenberg

Please note that dockstore-cgpwgs currently has the filtering bug (0.1.1) but I hope to resolve this later this week.

**Comment by keiranmraine** [comment]
1.0.2 has been released in the replacement repository.

Please see the [dockstore-cgpwgs](https://github.com/cancerit/dockstore-cgpwgs) repository and [dockstore.org](https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpwgs) integration.

This repository is soon to be retired.
