### ISSUE TITLE
Caveman filtering and flagging

### ISSUE THREAD

**Issue by markdunning** [cancerit/cgpbox#9]
Hello,

We are interested in using the cgpbox container to teach a workshop on the analysis of somatic mutations. However, we're struggling to see what filtering is being performed on the caveman calls.

Running the container on the example dataset (ftp://ftp.sanger.ac.uk/pub/cancer/cgpbox/testdata.tar) yields 2027 calls in the file "HCC1143_vs_HCC1143_BL.muts.ids.vcf.gz"; which I presume are the raw somatic calls before filtering?

In the file "HCC1143_vs_HCC1143_BL.flagged.muts.vcf.gz" there are still 2027 calls, however the only change seems to be that the FILTER flag has changed from "." to PASS. In other words, all the calls in HCC1143_vs_HCC1143_BL.flagged.muts.vcf.gz are still passing the filter.

Is this the expected behaviour? It seems as though the caveman filtering step is no filtering / flagging anything?

Do I need to run the script cgpFlagCaVEMan.pl manually to achieve filtering?

Regards,

Mark

**Comment by markdunning** [comment]
Seems to be a problem with the file `/opt/wtsi-cgp/lib/perl5/auto/share/dist/cgpCaVEManPostProcessing/human/flag.vcf.config.ini`

`/usr/bin/perl /opt/wtsi-cgp/bin/cgpFlagCaVEMan.pl -i /datastore/output/HCC1143_vs_HCC1143_BL/caveman/HCC1143_vs_HCC1143_BL.muts.ids.vcf -o /datastore/output/HCC1143_vs_HCC1143_BL/caveman/HCC1143_vs_HCC1143_BL.flagged.muts.vcf -s 'HUMAN' -m /datastore/output/tmp/HCC1143.bam -n /datastore/output/tmp/HCC1143_BL.bam -b /datastore/reference_files/caveman/flagging -g /datastore/output/HCC1143_vs_HCC1143_BL/pindel/HCC1143_vs_HCC1143_BL.germline.bed -umv /datastore/reference_files/caveman -ref /datastore/reference_files/genome.fa.fai -t WGS`

No flagList found in /opt/wtsi-cgp/lib/perl5/auto/share/dist/cgpCaVEManPostProcessing/human/flag.vcf.config.ini for section HUMAN_GENOME FLAGLIST. No flagging will be done. at /opt/wtsi-cgp/bin/cgpFlagCaVEMan.pl line 761.
    main::getConfigParams('HASH(0x23ac778)') called at /opt/wtsi-cgp/bin/cgpFlagCaVEMan.pl line 650
    main::setupFromConfig('HASH(0x23ac778)') called at /opt/wtsi-cgp/bin/cgpFlagCaVEMan.pl line 139
    main::main('HASH(0x23ac778)') called at /opt/wtsi-cgp/bin/cgpFlagCaVEMan.pl line 123
    eval {...} called at /opt/wtsi-cgp/bin/cgpFlagCaVEMan.pl line 122

**Comment by keiranmraine** [comment]
Hi,

Looks like you've uncovered a bug.  Despite passing `-t WGS` it is looking for `*_GENOME`.

For some reason the code changes `-t WGS` to `GENOME` and expects this in the config file instead of `WXS` which is what is currently in place.

I need to check with the primary author (@drjsanger) but should be able to sort this tomorrow once confirmed there won't be an unexpected knock-on.

Thanks for reporting this

**Comment by keiranmraine** [comment]
Actually looks like this has already been fixed, I'll kick of a new build

**Comment by keiranmraine** [comment]
Sorry, do need to confer with @drjsanger, `cgpFlagCaveman.pl` and `flagCaveman.pl`differ and will need to confirm correct route.

**Comment by markdunning** [comment]
That's great. Many thanks for looking into it quickly and for the reply.

**Comment by keiranmraine** [comment]
Hi, are you building from the Dockerfile or pulling from quay.io?  I can possibly do this by fixing the config and explicitly defining.

**Comment by markdunning** [comment]
I am pulling the container from quay.io. Thanks

**Comment by ghost** [comment]
I've made a bugfix release to [cgpCaVEManPostProcesisng](https://github.com/cancerit/cgpCaVEManPostProcessing/releases/tag/1.6.5) that fixes the issue.

**Comment by keiranmraine** [comment]
Building and testing now, taken a little longer than planned due to ENA going down.

**Comment by markdunning** [comment]
It looks as though the container has been re-built now?

**Comment by keiranmraine** [comment]
Yes, but only a specific branch:

docker pull quay.io/wtsicgp/cgp_in_a_box:logProgressNames

**Comment by keiranmraine** [comment]
@markdunning I'm currently building a new test dataset which runs in a more sensible time frame with the updated ASCAT code (the total run time was over 9 hours with the original version).  Hoping to get it all finalised and submitted for a test run later today.  Release by the end of the week if all goes to plan.

**Comment by keiranmraine** [comment]
Packaging for release now.  I highly recommend you use some non-Cell line data for your runs as the run time on Cell-lines for ASCAT (copy number) are very long.  I'll continue to try and get run time down but the current test set isn't any better than before (actually even longer).

**Comment by markdunning** [comment]
Many thanks for the fix. Regards, Mark
